
classdef buttons < ros.Message
    %buttons MATLAB implementation of conveyor_description_pkg/buttons
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'conveyor_description_pkg/buttons' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '222640963a46f585d04631e655f8bdf2' % The MD5 Checksum of the message definition
        PropertyList = { 'Angle' 'Rb' } % List of non-constant message properties
        ROSPropertyList = { 'angle' 'rb' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Angle
        Rb
    end
    methods
        function set.Angle(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'buttons', 'Angle');
            obj.Angle = single(val);
        end
        function set.Rb(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'buttons', 'Rb');
            obj.Rb = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.conveyor_description_pkg.buttons.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.conveyor_description_pkg.buttons(strObj);
        end
    end
end
