<?xml version="1.0"?>
<robot name="conveyor" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="$(find conveyor_description_pkg)/urdf/wheel_joints.urdf.xacro" />

    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/conveyor</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>

    <!-- BASE-FOOTPRINT -->
    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link
    origin -->
    <link name="base_footprint">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
    </link>

    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>


    <!-- BASE-LINK -->
    <!--Actual
    body/chassis of the robot-->
    <link name="base_link">
        <inertial>
            <mass value="${base_mass}" />
            <origin xyz="0 0 0" />
            <xacro:box_inertia m="${base_mass}" w="${base_length}" h="${base_length}"
                d="${base_height}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_length} ${base_height}" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <box size="${base_length} ${base_length} ${base_height}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>


    <!-- Wheel 1 -->
    <xacro:servo front="front" right="left" parent="base_link" axisX="1" axisY="1"
        angle="${3*M_PI/4}" /> <!-- ${-M_PI/4} -->
    <xacro:wheel fb="front" lr="left" parent="servo_front_left_link" translateX="0" translateY="0"
        translateZ="${-base_height-0.0075}" flipY="1" flipX="0" rot="-1" />
    <!-- Wheel 2 -->
    <xacro:servo front="front" right="right" parent="base_link" axisX="1" axisY="-1"
        angle="${M_PI/4}" /> <!-- ${5*M_PI/4} -->
    <xacro:wheel fb="front" lr="right" parent="servo_front_right_link" translateX="0" translateY="0"
        translateZ="${-base_height-0.0075}" flipY="1" flipX="1" rot="1" />
    <!-- Wheel 3 -->
    <xacro:servo front="back" right="left" parent="base_link" axisX="-1" axisY="1"
        angle="${5*M_PI/4}" /> <!-- ${M_PI/4} -->
    <xacro:wheel fb="back" lr="left" parent="servo_back_left_link" translateX="0" translateY="0"
        translateZ="${-base_height-0.0075}" flipY="1" flipX="0" rot="-1" />
    <!-- Wheel 4 -->
    <xacro:servo front="back" right="right" parent="base_link" axisX="-1" axisY="-1"
        angle="${-M_PI/4}" /> <!-- ${3*M_PI/4} -->
    <xacro:wheel fb="back" lr="right" parent="servo_back_right_link" translateX="0" translateY="0"
        translateZ="${-base_height-0.0075}" flipY="1" flipX="1" rot="1" />


    <!-- laser -->

    <link name="hokuyo_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${hokuyo_size}" />
            </geometry>
            <material name="Blue" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${hokuyo_size}" />
            </geometry>
        </collision>
    </link>

    <joint name="hokuyo_joint" type="fixed">
        <origin xyz="${base_length/2} 0 ${-base_height+0.005}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="hokuyo_link" />
    </joint>

    <gazebo reference="hokuyo_link">
        <material>Gazebo/Blue</material>
        <turnGravityOff>false</turnGravityOff>
        <sensor type="ray" name="head_hokuyo_sensor">
            <origin xyz="${base_length/2} 0 ${-base_height+0.005}" rpy="0 0 " />
            <visualize>false</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.570796</min_angle>
                        <max_angle>1.570796</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>20.0</max>
                    <resolution>0.001</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>hokuyo_link</frameName>
            </plugin>
        </sensor>
    </gazebo>


</robot>