<?xml version="1.0"?>
<robot name="conveyor" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- PROPERTY LIST -->

    <!-- Main Body Box -->
    <xacro:property name="base_length" value="0.255" /> <!-- in m-->
    <xacro:property name="base_height" value="0.04" /> <!-- in m-->
    <xacro:property name="base_mass" value="10" /> <!-- in kg-->


    <!-- caster wheel radius and height -->
    <!-- caster wheel mass -->
    <xacro:property name="servo_cube" value="0.03" /> <!-- in m-->
    <xacro:property name="servo_mass" value="2.5" /> <!-- in kg-->

    <!-- Hokuyo Laser scanner -->
    <!-- <xacro:property name="hokuyo_size" value="0.01 0.05 0.02" /> -->
    <xacro:property name="hokuyo_size" value="0.04" />


    <xacro:include filename="$(find conveyor_description_pkg)/urdf/wheel_joints.urdf.xacro" />

    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>

    <!-- BASE-FOOTPRINT -->
    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link
    origin -->
    <link name="base_footprint">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
    </link>

    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>


    <!-- BASE-LINK -->
    <!--Actual
    body/chassis of the robot-->
    <link name="base_link">
        <inertial>
            <mass value="${base_mass}" />
            <origin xyz="0 0 0" />
            <xacro:box_inertia m="${base_mass}" w="${base_length}" h="${base_length}"
                d="${base_height}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_length} ${base_height}" />
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <box size="${base_length} ${base_length} ${base_height}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <!-- palla -->
    <link name="ball_link">
        <inertial>
            <mass value="0.0000000001" />
            <origin xyz="0 0 0" />
            <xacro:box_inertia m="0.0000000001" w="0.0000000001" h="0.0000000001"
                d="0.0000000001" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
            <material name="White" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0 " />
            <geometry>
                <sphere radius="0.0000000001"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="ball_link">
        <material>Gazebo/Red</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <joint name="ball_link" type="fixed">
        <origin xyz="-0.2 0  0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="ball_link" />
    </joint>




    <!-- Wheel 1 -->
    <xacro:servo front="front" right="left" parent="base_link" axisX="1" axisY="1"
        angle="${3*M_PI/4}" /> <!-- ${-M_PI/4} -->
    <xacro:wheel fb="front" lr="left" parent="servo_front_left_link" translateX="0"
        translateY="-0.005"
        translateZ="${-base_height-0.011}" flipY="1" flipX="0" rot="-1" />
    <!-- Wheel 2 -->
    <xacro:servo front="front" right="right" parent="base_link" axisX="1" axisY="-1"
        angle="${M_PI/4}" /> <!-- ${5*M_PI/4} -->
    <xacro:wheel fb="front" lr="right" parent="servo_front_right_link" translateX="0"
        translateY="-0.005"
        translateZ="${-base_height-0.011}" flipY="1" flipX="1" rot="1" />
    <!-- Wheel 3 -->
    <xacro:servo front="back" right="left" parent="base_link" axisX="-1" axisY="1"
        angle="${5*M_PI/4}" /> <!-- ${M_PI/4} -->
    <xacro:wheel fb="back" lr="left" parent="servo_back_left_link" translateX="0"
        translateY="-0.005"
        translateZ="${-base_height-0.011}" flipY="1" flipX="0" rot="-1" />
    <!-- Wheel 4 -->
    <xacro:servo front="back" right="right" parent="base_link" axisX="-1" axisY="-1"
        angle="${-M_PI/4}" /> <!-- ${3*M_PI/4} -->
    <xacro:wheel fb="back" lr="right" parent="servo_back_right_link" translateX="0"
        translateY="-0.005"
        translateZ="${-base_height-0.011}" flipY="1" flipX="1" rot="1" />


    <!-- laser -->
    <!-- <link name="hokuyo_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hokuyo_size}" length="${hokuyo_size/2}" />
            </geometry>
            <material name="Blue" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${hokuyo_size}" length="${hokuyo_size/2}" />
            </geometry>
        </collision>
    </link>

    <joint name="hokuyo_joint" type="fixed">
        <origin xyz="0 0 ${base_height/2+hokuyo_size/4}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="hokuyo_link" />
    </joint>

    <gazebo reference="hokuyo_link">
        <material>Gazebo/Blue</material>
        <turnGravityOff>false</turnGravityOff>
        <sensor type="ray" name="head_hokuyo_sensor">
            <origin xyz="${base_length/2} 0 ${-base_height}" rpy="0 0 " />
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.141592</min_angle> 
                        <max_angle>3.141592</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>20.0</max>
                    <resolution>0.001</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>hokuyo_link</frameName>
            </plugin>
        </sensor>
    </gazebo> -->

    <!-- Revolute joint -->
    <link name="camera_revolute_link"></link>
    <joint name="camera_joint" type="revolute">
        <parent link="base_link" />
        <child link="camera_revolute_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-3.14" upper="3.14" effort="50" velocity="10" />
    </joint>
    <!-- Transmission joint camera -->
    <transmission name="camera_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="camera_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="camera_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <!-- Camera RGBD realsense d435i -->
    <!-- github: https://github.com/m-tartari/realsense_gazebo_description?tab=readme-ov-file -->
    <xacro:arg name="robotns" default="conveyor" />
    <xacro:include filename="$(find realsense_gazebo_description)/urdf/_d435i.urdf.xacro"/>
    <xacro:sensor_d435i parent="camera_revolute_link" name="/$(arg robotns)/D435i_camera" topics_ns="$(arg robotns)/D435i_camera"> 
      <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
    </xacro:sensor_d435i>

    <gazebo>
        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>50.0</updateRate>
            <bodyName>base_link</bodyName>
            <topicName>ground_truth/state</topicName>
            <gaussianNoise>0.01</gaussianNoise>
            <frameName>world</frameName>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
    </gazebo>


</robot>